In [1]:
# Импортируем библиотеку NumPy и даём ей стандартное сокращение np
import numpy as np


In [2]:
# Создаём массив из обычного Python-списка
# NumPy автоматически преобразует список в массив
a = np.array([1, 2, 3, 4])
a


array([1, 2, 3, 4])

In [7]:
# Создаём массив, заполненный нулями
# zeros принимает форму массива (кол-во строк и столбцов)
z = np.zeros((2, 3))
z


array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# Создаём массив, заполненный единицами
o = np.ones(5)
o


array([1., 1., 1., 1., 1.])

In [9]:
# Создаём последовательность чисел с помощью arange
# от 0 до 10 (не включая), шаг — 2
r = np.arange(0, 10, 2)
r


array([0, 2, 4, 6, 8])

In [10]:
# Выводим форму массива и тип данных
print("Форма массива a:", a.shape)   # Количество элементов (и измерений)
print("Тип данных массива a:", a.dtype)  # Тип данных внутри массива


Форма массива a: (4,)
Тип данных массива a: int64


In [11]:
# Получение одного элемента массива
# Индексация начинается с нуля
print("Второй элемент массива a:", a[1])


Второй элемент массива a: 2


In [12]:
# Получение среза массива (подмассива)
# Берём элементы массива r со 2-го по 4-й (не включая последний индекс)
print("Срез массива r (элементы r[1:4]):", r[1:4])


Срез массива r (элементы r[1:4]): [2 4 6]


In [13]:
# Создаём второй массив такой же длины
b = np.array([10, 20, 30, 40])

# Поэлементное сложение двух массивов
print("Сложение a + b:", a + b)


Сложение a + b: [11 22 33 44]


In [14]:
# Умножение каждого элемента массива на число
print("a * 3:", a * 3)


a * 3: [ 3  6  9 12]


In [15]:
# Вычисление средней величины массива
print("Среднее значение массива b:", b.mean())


Среднее значение массива b: 25.0
